# Generated by Django 3.1.7 on 2021-07-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
