# Generated by Django 3.1.7 on 2021-07-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20210418_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='size',
        ),
    ]
